name: roboza-press
version: git
summary: A Bookmarker App built in rust that scrapes your google chrome saved bookmarks

description: |
  Roboza Press Is A Bookmarker App built in rust that scrapes you google chrome saved bookmarks and shows them in a good way with the ability to filter and search in them

  composable:
  - Filter Bookmarks.
  - Search in bookmarks
  - Navigate to your bookmarks easily

base: core18
confinement: devmode


parts:
  roboza-press:
    plugin: rust
    source: .
    build-packages:
      - gcc
      - make
      - pkg-config
      - openssl

apps:
  roboza-press:
    command: bin/roboza-press